package com.im.netty.domain.dto;

import lombok.Data;

/**
 * IM message base DTO.
 * <p>
 * The generic {@code T} represents the message body type:
 * <ul>
 *   <li>String — plain text or image URL</li>
 *   <li>List of {type, content} objects — mixed image+text content</li>
 * </ul>
 *
 * @see MallImMessageTypeEnum
 */
@Data
public class BaseIMMessageDTO<T> {

    /** Message unique ID, assigned by server (e.g. "IM_<uuid>") */
    private String msgId;

    /** Whether this message was generated by AI */
    private Boolean aiGenerate;

    /** Message type code */
    private Integer messageType;

    /** Sender user ID */
    private String senderId;

    /** Receiver user ID */
    private String receiverId;

    /**
     * Message body.
     * <pre>
     * Text:    "message": "hello"
     * Image:   "message": "https://img.url/photo.jpg"
     * Mixed:   "message": [{"type":"IMG","content":"url"}, {"type":"TEXT","content":"text"}]
     * </pre>
     */
    private T message;

    /** Message timestamp (millis), set by Netty server on receipt */
    private Long msgTime;

    /** Read status */
    private Boolean read;
}
